---
###################################################################################################
# PHP php-cli.ini php-fpm.ini php-fpm.conf settings
###################################################################################################


# -------------------------------------------------------------------------------------------------
# Global
# -------------------------------------------------------------------------------------------------
php_timeout: 120


# -------------------------------------------------------------------------------------------------
# php.ini
# -------------------------------------------------------------------------------------------------
php_settings_ini:
  # ---- Sane default ----
  cli:
    memory_limit: -1
    zlib_output_compression: 'On'
    realpath_cache_size: 32k
    realpath_cache_ttl: 7200
    always_populate_raw_post_data: -1
    max_input_vars: 10000
    session_gc_probability: 1
    opc_enabled: 1
    opc_validate_timestamps: 1

  # ---- Inherits from base ----
  fpm:
    memory_limit: 768M
    opc_enabled: 1
    opc_validate_timestamps: 1
    user_ini_filename: ""

# -------------------------------------------------------------------------------------------------
# php-fpm.conf
# -------------------------------------------------------------------------------------------------
php_settings_fpm:
  # ---- Sane default ----
  base:
    # Docker
    clear_env:                 'no'
    catch_workers_output:      'yes'
    # Timeouts
    request_terminate_timeout: "{{ php_timeout }}s"
    # Network
    listen:                    "[::]:9000"
    # Backlog
    listen_backlog:            1024
    # Logging
    log_level:                 notice
    error_log:                 /proc/self/fd/2
    access_log:                /proc/self/fd/2
    # Worker
    pm:                        dynamic
    pm_max_children:           10      # pm: dynamic, ondemand or static
    pm_start_servers:          4       # only for pm: dynamic (min_spare + (max_spare-min_spare)/2
    pm_min_spare_servers:      2       # only for pm: dynamic
    pm_max_spare_servers:      6       # only for pm: dynamic
    pm_max_requests:           500     # pm: dynamic or ondemand
    pm_process_idle_timeout:   10s     # only for pm: ondemand
    pm_status_path:            /status # only for pm: ondemand

    # User/Group
    user:                      www
    group:                     www
