---
###################################################################################################
# Docker: php-cli (docker stage: help)
###################################################################################################

#
# This file holds definition for all nntoan/docker-php:x.y-cli images
#

# The following specifies the order in which modules are being built.
env_php_extensions:
  - bcmath
  - bz2
  - calendar
  - exif
  - gd
  - gettext
  - intl
  - mysqli
  - opcache
  - pdo_mysql
  - redis
  - soap
  - sockets
  - sodium
  - sysvmsg
  - sysvsem
  - sysvshm
  - xsl
  - zip
  - pcntl