---
###################################################################################################
# Docker: php-cli (docker stage: help)
###################################################################################################

#
# This file holds definition for all nntoan/docker-php:x.y-cli images
#

# The following specifies the order in which modules are being built.
cli_base_packages:
  - apt-utils
  - cron
  - git
  - mariadb-client
  - nano
  - nodejs
  - python3
  - python3-pip
  - redis-tools
  - sendmail-bin
  - sendmail
  - sudo
  - unzip
  - vim
  - openssh-client

tools_enabled:
  - grunt-cli
  - gulp

tools_available:
  grunt-cli:
    disabled: []
    check: grunt --version | grep -E '[0-9][.0-9]+' || (grunt --version; false)
    all:
      type: npm
      package: "grunt-cli"
      binary: grunt
      version:
      build_dep: []
      run_dep: []
      pre:
      post:
  gulp:
    disabled: []
    check: gulp --version | grep -E '[0-9][.0-9]+' || (gulp --version; false)
    all:
      type: npm
      package: gulp
      binary: gulp
      version:
      build_dep: []
      run_dep: []
      pre:
      post:
