---

- name: generate Dockerfiles
  ansible.builtin.template:
    src:  "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: True
    mode:  0644
  with_items:
    - "{{ template_dockerfiles_varnish }}"
